### ISSUE TITLE
OSError: Google Drive quota exceeded

### ISSUE THREAD

**Issue by PrashantSaikia** [urielsinger/familyGan#2]
I get the following error when trying to run `run.py`:

```
Downloading https://drive.google.com/uc?id=1MEGjdvVpUsu1jB4zrXZN7Y4kBBOzizDQ ............ failed
Traceback (most recent call last):
  File "run.py", line 132, in <module>
    run_single_image(perc_param)
  File "run.py", line 77, in run_single_image
    _, aligned_latent = image2latent(imgs, iterations=ITER, init_dlatents=init_dlatent, args=perc_param,
  File "/Users/username/Downloads/familyGan-master/familyGan/pipeline.py", line 86, in image2latent
    config.init_generator(batch_size=batch_size)
  File "/Users/username/Downloads/familyGan-master/familyGan/config.py", line 58, in init_generator
    generator, Gs_network = get_generator(batch_size)
  File "/Users/username/Downloads/familyGan-master/familyGan/config.py", line 67, in get_generator
    with dnnlib.util.open_url(URL_FFHQ, cache_dir=config.cache_dir) as f:
  File "/Users/username/Downloads/familyGan-master/familyGan/stylegan_encoder/dnnlib/util.py", line 414, in open_url
    cache_dir, f = open_url_n_cache(url, cache_dir, num_attempts, verbose)
  File "/Users/username/Downloads/familyGan-master/familyGan/stylegan_encoder/dnnlib/util.py", line 381, in open_url_n_cache
    raise IOError("Google Drive quota exceeded")
OSError: Google Drive quota exceeded

```

So I manually downloaded the file from that Google drive link, but I do not know where to put it. Could you please point out the right directory to put the downloaded file `karras2019stylegan-ffhq-1024x1024.pkl` in? Thanks!

**Comment by urielsinger** [comment]
try `familyGan/familyGan/cache/karras2019stylegan-ffhq-1024x1024.pkl`

**Comment by Hisan-007** [comment]
@PrashantSaikia were you able to solve the issue ?
